DROP TABLE IF EXISTS PRODUCTS
DROP TABLE IF EXISTS MEMBERSHIPS
DROP TABLE IF EXISTS TRANSACTIONS
DROP TABLE IF EXISTS REWARDS

CREATE TABLE PRODUCTS IF NOT EXISTS(
    id SERIAL PRIMARY KEY,
    name VARCHAR,
    price INTEGER,
    stock INTEGER,
    type VARCHAR
)

CREATE TABLE MEMBERSHIPS IF NOT EXISTS(
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    point INTEGER,
    telephone INTEGER
)

CREATE TABLE TRANSACTIONS IF NOT EXISTS(
    id SERIAL PRIMARY KEY,
    customer VARCHAR,
    product_id INTEGER NOT NULL UNIQUE,
    quantity INTEGER,
    gross_price INTEGER,
    discount INTEGER,
    net_price INTEGER,
    FOREIGN KEY(product_id) REFERENCES PRODUCTS(id)
)

CREATE TABLE REWARDS IF NOT EXISTS(
    id SERIAL PRIMARY KEY,
    name VARCHAR,
    point INTEGER,
)